# Generated by Django 3.0.5 on 2020-06-05 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FE_Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(db_index=True, default='semester', max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'FE_Semester',
                'verbose_name_plural': 'FE_Semesters',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_name', models.CharField(db_index=True, default='semester', max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Semester',
                'verbose_name_plural': 'Semesters',
            },
        ),
        migrations.CreateModel(
            name='mech_qp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.Semester')),
            ],
            options={
                'verbose_name': 'mech_qp',
                'verbose_name_plural': 'mech_qps',
            },
        ),
        migrations.CreateModel(
            name='mech_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.Semester')),
            ],
            options={
                'verbose_name': 'mech_note',
                'verbose_name_plural': 'mech_notes',
            },
        ),
        migrations.CreateModel(
            name='FE_qp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.FE_Semester')),
            ],
            options={
                'verbose_name': 'FE_qp',
                'verbose_name_plural': 'FE_qps',
            },
        ),
        migrations.CreateModel(
            name='FE_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.FE_Semester')),
            ],
            options={
                'verbose_name': 'FE_note',
                'verbose_name_plural': 'FE_notes',
            },
        ),
        migrations.CreateModel(
            name='comp_qp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.Semester')),
            ],
            options={
                'verbose_name': 'comp_qp',
                'verbose_name_plural': 'comp_qps',
            },
        ),
        migrations.CreateModel(
            name='comp_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.Semester')),
            ],
            options={
                'verbose_name': 'comp_note',
                'verbose_name_plural': 'comp_notes',
            },
        ),
        migrations.CreateModel(
            name='civil_qp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.Semester')),
            ],
            options={
                'verbose_name': 'civil_qp',
                'verbose_name_plural': 'civil_qps',
            },
        ),
        migrations.CreateModel(
            name='civil_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='i', max_length=200)),
                ('filename', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='media/Docs')),
                ('slug', models.SlugField(unique=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='helpmate.Semester')),
            ],
            options={
                'verbose_name': 'civil_note',
                'verbose_name_plural': 'civil_notes',
            },
        ),
    ]
