# Generated by Django 3.0.5 on 2020-06-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpmate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='civil_note',
            name='branch',
            field=models.CharField(default='CIVIL ENGINEEERING', max_length=200),
        ),
        migrations.AddField(
            model_name='civil_qp',
            name='branch',
            field=models.CharField(default='CIVIL ENGINEEERING', max_length=200),
        ),
        migrations.AddField(
            model_name='comp_note',
            name='branch',
            field=models.CharField(default='COMPUTER ENGINEEERING', max_length=200),
        ),
        migrations.AddField(
            model_name='comp_qp',
            name='branch',
            field=models.CharField(default='COMPUTER ENGINEEERING', max_length=200),
        ),
        migrations.AddField(
            model_name='fe_note',
            name='branch',
            field=models.CharField(default='FIRST-YEAR ENGINEEERING', max_length=200),
        ),
        migrations.AddField(
            model_name='fe_qp',
            name='branch',
            field=models.CharField(default='FIRST-YEAR ENGINEEERING', max_length=200),
        ),
        migrations.AddField(
            model_name='mech_note',
            name='branch',
            field=models.CharField(default='MECHANICAL ENGINEEERING', max_length=200),
        ),
        migrations.AddField(
            model_name='mech_qp',
            name='branch',
            field=models.CharField(default='MECHANICAL ENGINEEERING', max_length=200),
        ),
    ]
