# Generated by Django 3.0.5 on 2020-06-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpmate', '0004_auto_20200607_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_upload_notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('branch', models.CharField(max_length=200)),
                ('semester', models.CharField(max_length=100)),
                ('ufile', models.FileField(upload_to='media/user_uploads')),
                ('text', models.TextField()),
            ],
        ),
    ]
