# Generated by Django 3.0.6 on 2020-06-10 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpmate', '0006_auto_20200610_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_upload_notes',
            name='email',
            field=models.EmailField(max_length=300),
        ),
    ]
